import { Td } from "./td";

export const TDS: Td[] = [
  /*{itdId:1, mumId:1, mtcId:1, mumName:'购买车位-查询物业项目', itdName:'TC_01_GZH_001_001', itdCols:'maProvide#maName#begin#length#token#location', itdValues:'深圳市#小蔡的物业项目#1#1#Ffx2b2347K34xzkGQNQipfyJ6tgDSVIsYqZnc02ZbHQntHCnW6qDhLTncrOr7FiI1113c24d8d50475ead7fccd69e5311c6170904180927uPV2IMhaK1JIzNljXz#深圳市', itdParamTypes:'String#String#int #int#String#String', itdType: 0, itdExpectTime:100, itdExpectResult:'XXXXX', itdExpectResultType:'json', itdSql:'select maProvide, maName, location from xx_table where maProvide="深圳市" and maName="小蔡的物业项目";', itdSqlExpectResult:'{"深圳市","小蔡的物业项目","深圳市";"深圳市","小蔡的物业项目","深圳市"}' },
  {itdId:2, mumId:1, mtcId:1, mumName:'购买车位-查询物业项目', itdName:'TC_01_GZH_001_002', itdCols:'maProvide#maName#begin#length#token#location', itdValues:'12#aa#aa#12', itdParamTypes:'String#int#int#String', itdType: 0, itdExpectTime:100, itdExpectResult:'XXXXX', itdExpectResultType:'json', itdSql:'xxxxx', itdSqlExpectResult:'xxxxxx' },
  {itdId:3, mumId:2, mtcId:1, mumName:'购买车位-查询物业项目设备', itdName:'TC_01_GZH_002_001', itdCols:'maId#begin#length#token', itdValues:'12#aa#aa#12', itdParamTypes:'String#int#int#String', itdType: 0, itdExpectTime:100, itdExpectResult:'XXXXX', itdExpectResultType:'json', itdSql:'xxxxx', itdSqlExpectResult:'xxxxxx' },
  {itdId:4, mumId:2, mtcId:1, mumName:'购买车位-查询物业项目设备', itdName:'TC_01_GZH_002_002', itdCols:'maId#begin#length#token', itdValues:'12#aa#aa#12', itdParamTypes:'String#int#int#String', itdType: 0, itdExpectTime:100, itdExpectResult:'XXXXX', itdExpectResultType:'json', itdSql:'xxxxx', itdSqlExpectResult:'xxxxxx' },
  {itdId:5, mumId:3, mtcId:2, mumName:'新增基本设备-新增基本设备类型', itdName:'TC_02_FL_001_001', itdCols:'mmName#mmQuantity#mmMaxWeight#mmCharging#mmSizeX#mmSizeY#mmSizeZ#mmSuggestMonthlyPrice#mmSuggestDailyPrice#mmBookedDailyPrice', itdValues:'12#aa#aa#12', itdParamTypes:'String#int#int#String', itdType: 0, itdExpectTime:100, itdExpectResult:'XXXXX', itdExpectResultType:'json', itdSql:'xxxxx', itdSqlExpectResult:'xxxxxx' },
  {itdId:6, mumId:3, mtcId:2, mumName:'新增基本设备-新增基本设备类型', itdName:'TC_02_FL_001_002', itdCols:'mmName#mmQuantity#mmMaxWeight#mmCharging#mmSizeX#mmSizeY#mmSizeZ#mmSuggestMonthlyPrice#mmSuggestDailyPrice#mmBookedDailyPrice', itdValues:'12#aa#aa#12', itdParamTypes:'String#int#int#String', itdType: 0, itdExpectTime:100, itdExpectResult:'XXXXX', itdExpectResultType:'json', itdSql:'xxxxx', itdSqlExpectResult:'xxxxxx' },
  {itdId:7, mumId:4, mtcId:2, mumName:'修改设备类型费率1', itdName:'TC_02_FL_002_001', itdCols:'mmId#type#price#value', itdValues:'12#aa#aa#12', itdParamTypes:'String#int#int#String', itdType: 0, itdExpectTime:100, itdExpectResult:'XXXXX', itdExpectResultType:'json', itdSql:'xxxxx', itdSqlExpectResult:'xxxxxx' },
  {itdId:8, mumId:4, mtcId:2, mumName:'修改设备类型费率1', itdName:'TC_02_FL_002_002', itdCols:'mmId#type#price#valuee', itdValues:'12#aa#aa#12', itdParamTypes:'String#int#int#String', itdType: 0, itdExpectTime:100, itdExpectResult:'XXXXX', itdExpectResultType:'json', itdSql:'xxxxx', itdSqlExpectResult:'xxxxxx' },*/
];
